### PR TITLE
Fix drawing offset

### PR DESCRIPTION
**Pull request by JJJollyjim**
Also rounds the end of lines for fancyness

### CODE REVIEW

**Comment by JJJollyjim** [comment]
Hurry up scrub maintainer mergs pls

**Comment by JJJollyjim** [comment]
I'll get linus to berate you

**Comment by NickGeek** [comment]
Haha. Thanks

**Comment by NickGeek** [comment]
Being berated by Linus is just a state of being

**Comment by JJJollyjim** [comment]
BTW I fucked up your indentation something awful

**Comment by JJJollyjim** [comment]
I think emacs is set to 4 spaces...

**Comment by JJJollyjim** [comment]
Okay if I PR with an editorconfig?

**Comment by NickGeek** [comment]
Sure. My indentation looks fine btw

**Comment by NickGeek** [comment]
Nvm, I see some issues. Just fixed them

**Pull request merged**
